### ISSUE TITLE
v3.0.0: extend or overwrite watch targets

### ISSUE THREAD

**Issue by renestalder** [arnoson/kirby-vite#11]
Previously to v3.0.0, I could tell the live reload plugin to watch additional targets. It seems like this option is gone since 3.0.0 or not documented anymore.

I use Twig templates instead of raw PHP templates, so I want to watch them for changes.

**Comment by arnoson** [comment]
You can pass custom watch paths in [vite-plugin-kirby](https://github.com/arnoson/vite-plugin-kirby#watch-files) I'll add a note in the readme!
