### ISSUE TITLE
Compatibility to Kirby 3.8.0.0 

### ISSUE THREAD

**Issue by macx** [arnoson/kirby-vite#12]
This plugin is not working with Kirby 3.8.0.0 because of the use of `Kirby\Http\Server`, which is deprecated.

See [changelog](https://getkirby.com/releases/3.8#changes-deprecated)

**Comment by macx** [comment]
Sorry, my fault.

**Comment by arnoson** [comment]
I'm not using `Kirby\Http\Server` or am I missing something?
