### ISSUE TITLE
`templates/default/index.js` is not a manifest entry.

### ISSUE THREAD

**Issue by alancwoo** [arnoson/kirby-vite#14]
I'm not sure if it's related to #13 but I'm having this error when trying to load the site:

`'templates/default/index.js' is not a manifest entry.`

<img width="620" alt="image" src="https://user-images.githubusercontent.com/1481890/205680339-ded95b81-8d7d-4012-b8ad-6821dd50bbb7.png">

I've updated to the latest version `3.0.3` with no luck, with Kirby `3.8.2`

I have the `public/index.php` like so:

```
<?php

$_SERVER['HTTPS'] = getenv('APP_ENV') == 'production';

include __DIR__ . '/../vendor/autoload.php';

$kirby = new Kirby\Cms\App([
  'roots' => [
    'index'    => __DIR__,
    'base'     => $base = dirname(__DIR__),
    'content'  => $base . '/content',
    'site'     => $base . '/site',
    'storage'  => $storage = $base . '/storage',
    'accounts' => $storage . '/accounts',
    'cache'    => $storage . '/cache',
    'sessions' => $storage . '/sessions',
  ]
]);

echo $kirby->render();

```

**Comment by arnoson** [comment]
So you are using the [multi page kit](https://github.com/arnoson/kirby-vite-multi-page-kit)?
Your problem seems to the same as this issue: https://github.com/arnoson/kirby-vite-multi-page-kit/issues/9
Can you try out the solution there? At some point I will update the starter kit to match the solution in the issue.

**Comment by alancwoo** [comment]
That's correct, I'm using the multipage kit.

I'm sorry I didnt' see #9, I actually tried the solution, but it resulted in an odd duplication in looking for the entry, something like: `templates/templates/default/index.js/index.js`

I solved it by creating empty js/css files for the `default` template and it is working now, thank you for the quick response!

**Comment by arnoson** [comment]
I updated kirby-vite, it now exposes the vite manifest, so you can check if an entry exists before importing it. I updated the multi-page kit accordingly. If you have an existing project, update kirby-vite and use the header and footer snippet from the latest multi-page kit version.
