### ISSUE TITLE
Deployed build references localhost?

### ISSUE THREAD

**Issue by alancwoo** [arnoson/kirby-vite#2]
I’ve built for production with ‘npm run build’ but noticed the deployed site is referencing localhost for the js and css assets. It works locally but am wondering if I am missing some amount of configuration or how to best go about debugging this?

eg, footer.php

`<?= vite()->js() ?>` results in `<script src="http://localhost:3000/index.js" type="module"></script>` instead of the built files.

**Comment by alancwoo** [comment]
Ah ok, so it looks like it has to do with https://github.com/arnoson/kirby-vite/blob/fcf9a6199a5c6d32f6940a6267dd1274394b546a/lib/Vite.php#L68

So it looks like I had perhaps run the dev server which created the lockfile and didn't build/remove it before rsyncing.

Removing `/src/.lock` on the remove server fixed the issue.

**Comment by arnoson** [comment]
Ah great, I was just writing a reply. Happy to hear that everything works now!

**Comment by arnoson** [comment]
You could also add an [separate config](https://getkirby.com/docs/guide/configuration#multi-environment-setup) for the remote server in which you set `arnoson.kirby-vite.dev` to false. Setting this option will always have priority over the `.lock` file check.

**Comment by alancwoo** [comment]
Ah right, that makes a lot more sense (to use the config), thanks for the response and the great plugin :)
