### ISSUE TITLE
srcset rendering issues

### ISSUE THREAD

**Issue by vitali-sigel** [arnoson/kirby-vite#23]
Hey, i've come across some strange issues when trying to use responsive images using the srcset attribute within a picture element. 
I am following this Kirby cookbook recipe: https://getkirby.com/docs/cookbook/performance/responsive-images
Kirby-vite has issues the required avif and webp images correctly.
Trying the exact same thing with a kirby plainkit behaves exactly like it should.

I'm in a hurry now, if this is interessting to someone, i will gladly explain in more detail!

Thanks!

**Comment by arnoson** [comment]
Are you importing the image in js/css or just via php like in the cookbook?
This kit doesn't do anything special to images, so it should behave like the normal kirby plain kit. What issues/errors do you get?

**Comment by arnoson** [comment]
Closing this as I need more feedback. Feel free to reopen it.
