### ISSUE TITLE
Custom folder setup creates issue with locating the manifest

### ISSUE THREAD

**Issue by fvsch** [arnoson/kirby-vite#26]
Hi there. Thanks for this plugin!

I have a custom folder setup for Kirby with a `public` subfolder acting as my web root:

```
content/
  …
public/
  .htaccess
  index.php
  media/
  dist/
site/
  …
vendor/
  …
composer.json
package.json
vite.config.js
```

That's actually recommended in this plugin's README:

> Make sure you use a modern [public folder structure](https://getkirby.com/docs/guide/configuration#custom-folder-setup__public-folder-setup).

Let's say I have configured `vite.config.js` like this:

```js
export default {
  base: '/dist/',
  build: {
    outDir: 'public/dist',
  },
};
```

The manifest will be written to `/path/to/project/public/dist/manifest.json`.

But if I configure this plugin on the PHP side with the same `outDir` value as in the Vite config, like this:

```php
return [
  'arnoson.kirby-vite' => [
    'outDir' => 'public/dist',
  ]
];
```

Then this plugin fails to find the `manifest.json` file. That's because it's using this code:

```php
$manifestPath = kirby()->root('index') . '/' . option('arnoson.kirby-vite.outDir', 'dist') . '/manifest.json';
```

Which will result in this path:

```
/path/to/project/public/public/dist/manifest.json
```

To make it work, I have to set `'outDir' => 'dist'` in the PHP config, instead of `'outDir' => 'public/dist'`. Which works, but now I have a mismatch with the Vite config, which doesn't follow what the docs for this plugin says to do. ^^

Another possible workaround is to configure the `'index'` root to the project root, instead of the document root, but that contradicts [the Kirby docs for the `'index'` root](https://getkirby.com/docs/reference/system/roots/index) and the [custom folder setup example](https://getkirby.com/docs/guide/configuration#custom-folder-setup__public-folder-setup) that this plugin recommends. I’m also not sure if it might break some stuff.

I think the underlying issue is that Kirby doesn't have a concept of a "project root" which is not the "document root". And in practice, it looks like Kirby is treating the `'index'` root as the root of the whole project, where Kirby will look for the `content`, `media` and `site` folders if those roots are not explicitly defined. So maybe it's the Kirby docs that are wrong, and the "index" root is not strictly a "document root" and the custom folder setup example is kinda wrong? (That example does configure roots named "base" and "storage" which [just don't exist in the docs](https://getkirby.com/docs/guide/configuration#custom-folder-setup__all-configurable-roots).)

**Comment by arnoson** [comment]
Hi, have you tried the [basic kit](https://github.com/arnoson/kirby-vite-basic-kit)? This should basically be your setup, otherwise I can look into this next week!

**Comment by fvsch** [comment]
Nope, hadn't tried it.

Looks like it works by having different values for the `outDir` option:

| Vite config | kirby-vite config |
| --- | --- |
| `'build.outDir': 'public/dist'` | `'arnoson.kirby-vite.outDir' => 'dist'` |

So it looks like this part of the README might need an extra warning for the public folder setup case:
https://github.com/arnoson/kirby-vite/blob/0718e1d19605d9c9b66637e52015bc0e75a4079d/README.md?plain=1#L85

**Comment by fvsch** [comment]
One thing I'm puzzled by, looking at the source for the Vite class:

1. When looking for the `.dev` file, the logic uses the `base` root and falls back to the `index` root: https://github.com/arnoson/kirby-vite/blob/0718e1d19605d9c9b66637e52015bc0e75a4079d/lib/Vite.php#L20-L21

2. But when looking for the `manifest.json` file, the logic uses the `index` root only: https://github.com/arnoson/kirby-vite/blob/0718e1d19605d9c9b66637e52015bc0e75a4079d/lib/Vite.php#L51

If both used the `base` root, then it would be possible to have the same `outDir` value in the Vite config and in the kirby-vite config.

Though note that I have tried it, and it kinda works, but then this plugin cannot construct correct URLs because it will try to link to `/public/dist/assets/…` instead of `/dist/assets/…`. That's because it used the `outDir` option to construct URLs, unlike Vite which uses the `base` option.

**Comment by arnoson** [comment]
okay thanks for investigating this!

**Comment by arnoson** [comment]
I have thought about it and for me it makes sense watching for the `manifest.json` inside index root, because the manifest is coupled to the assets and the assets can only be inside index root, otherwise the server can't access them.

For the `.dev` it make sense to look into the "real" root, that is index for flat setups and base for public folder setups, because by definition the `.dev` should be in the projects root folder.

Vite's `build.outDir` option is relative to the cwd, and therefore `public/dist` makes sense.

I guess I wont make `arnoson.kirby-vite.outDir` relative to index instead of base, since it will only complicate the code (like having to get rid of `/public` again when constructing URLs as you mentioned.

So this leaves changing the docs, do you have any suggestions for the wording?

**Comment by arnoson** [comment]
Closing this, as all options are now synced from the `vite.config.js` file
