### ISSUE TITLE
How to call methods? (Scope/Namespacing?)

### ISSUE THREAD

**Issue by alancwoo** [arnoson/kirby-vite#3]
Hello again, sorry for another question - say I have something like `src/templates/home/index.js`:

```
import '@/index.js'
import './index.css'

const hello = () => {
	alert('Hello!')
}
```

and want to call the method from the php script at `templates/home.php`:

```
<span onclick="hello()">Hello</span>
```

What is the right way to reference this method? (it is undefined in the general scope).

**Comment by arnoson** [comment]
In this case you can either expose your method to the global scope explicitly
```js
window.hello = () => alert('Hello!')
```
Which kind of defeats the whole purpose of using javascript modules, which is not to pollute the global space. So I would rather register the click event in your javascript file.
```html
<!-- templates/home.php -->
<span class="hello-button">hello<span>
```
```js
// @/index.js
const hello = () => alert('Hello!')
document.querySelector('.hello-button').addEventListener('click', hello)
```
