### ISSUE TITLE
Is there a way to install it via git submodule?

### ISSUE THREAD

**Issue by dustsucker** [arnoson/kirby-vite#30]
We have a big page using only submodules and want to integrate Some new stuff with svelte as web components is there a way to use it with submodules?

**Comment by arnoson** [comment]
I don't use submodules, so I'm not sure. But although this is a monorepo, it also acts as a normal repository (the `index.php` is linking to the actual kirby plugin located in `packages/kirby-vite`). So this should work, I guess. Are there any specific requirements for a repository so it can be used as a submodule?

**Comment by matteocontrini** [comment]
It seems to be working fine as a submodule.

Here's what I used to pin a specific version of the plugin with the submodule.

```
git submodule add https://github.com/arnoson/kirby-vite.git site/plugins/vite
cd site/plugins/vite && git checkout v5.3.0
```

And then commit in the parent repo.

**Comment by arnoson** [comment]
Great, thanks for the explanation @matteocontrini!
