### ISSUE TITLE
feat: allow dynamic manifest filename

### ISSUE THREAD

**Issue by arnoson** [arnoson/kirby-vite#35]
https://main.vitejs.dev/guide/migration

relevant:
- manifest is generated inside a `.vite` folder in `build.outDir`
- `https` option is dropped

**Comment by dekodesign** [comment]
If you're willing to override Vite 5's default configuration (and not use the `.vite` folder) I found that changing:

https://github.com/arnoson/kirby-vite/blob/94c1cd33594273e4cfd7818143d4b545440c50d0/packages/vite-plugin-kirby/src/index.ts#L57

to `return { build: { manifest: "manifest.json" } }`

will restore the "old" behavior.

For reference, manifest output appears to be controlled in Vite 5's config via:

https://github.com/vitejs/vite/blob/c936fb7381d0d1cbb7e4c7e92f9c73659187ab2e/packages/vite/src/node/plugins/manifest.ts#L155-L157

**Comment by arnoson** [comment]
ah thanks for investigating this, the docs weren't clear on that. I just released a new version of kirby vite that uses `.vite/manifest.json`, but it would be a good idea to add the dynamic manifest filename in the future
