### ISSUE TITLE
manifest.json not found

### ISSUE THREAD

**Issue by hansipete** [arnoson/kirby-vite#39]
Since yesterday I get a `manifest.json not found` error after `npm run build` the side and trying to access it. Resetting the vite.config.js to the one given in the example/ folder (with slight adjustments to make it work in my setup) does not fix it.

What does fix it is changing line 98 in Vite.php and removing `.vite/` from the path: `$manifestPath = "$index/$outDir/.vite/manifest.json";`

`npm run dev` works just fine

Is this some weird glitch on my side? Tried to reinstall the plugin but with no success...

**Comment by arnoson** [comment]
`.vite` was added in vite 5, did you make sure to install also the newest version of `vite-plugin-kirby`? It has Vite 5 as it's peer dependency. If the issue persists, can you tryout the [basic kit](https://github.com/arnoson/kirby-vite-basic-kit)?

**Comment by hansipete** [comment]
Thank you for your help! 

I found that I was still von vite 4.5. `npm i vite` does not install version 5 for me. `npm i -D vite`installs v5 as a devDependency though.

With vite 5 everything works as expected – thank you!
