### ISSUE TITLE
Help needed. Running Server in custom directory?

### ISSUE THREAD

**Issue by dannystarkDE** [arnoson/kirby-vite#40]
Hey,

I'm trying to run the setup in a custom folder structure.
So I have the config files etc in the root folder, but the installation itself in an "app" folder.

But I can't get it to run.

![20240121_103908_screenshot](https://github.com/arnoson/kirby-vite/assets/8641492/724dd9a4-53a8-42a7-a550-6cd1bd28fec8) 

In the package.json i changed the server command to:
`"server": "php -S localhost:8888 -t app/public server.php",`

in the server.php the root directory to:
`$root = __DIR__ . '/app/public';`

```
Then tried to edit vite.config.js:

import { resolve } from 'path'
import kirby from 'vite-plugin-kirby'

export default ({ mode }) => ({
  root: 'src',
  base: mode === 'development' ? '/app/' : '/app/dist/',

  build: {
    outDir: resolve(process.cwd(), 'app/public/dist'),
    emptyOutDir: true,
    rollupOptions: { input: resolve(process.cwd(), 'src/index.js', 'src/assets/css/app.scss') }
  },

  plugins: [kirby({
    watch: [
      '../site/templates/**/*.twig',
      '../site/(snippets|controllers|models)/**/*.php',
      '../content/**/*',
    ]
  })],
})
```

but still with the result:

```
[vite] error when starting dev server:
[vite] Error: ENOENT: no such file or directory, open 'site/config/vite.config.php'
[vite] npm run vite exited with code 1

```
Does anyone have any idea which files I need to edit?
Thanks a lot!

**Comment by arnoson** [comment]
I have little time at the moment, have you checked out the [plugin config](https://github.com/arnoson/kirby-vite#config)? Looks like you have to set the `kirbyConfigDir` and make sure that the plugin creates the `vite.config.php` in your Kirbys config folder

**Comment by dannystarkDE** [comment]
hey, thanks for your help. with the `kirbyConfigDir` I am now one step further.
Now I have the next error:

`str_starts_with(): Argument #1 ($haystack) must be of type string, bool given`

TypeError 
`…/site/plugins/kirby-vite/packages/kirby-vite/Vite.php12`



``` js
// My current vite.config.js:
import { resolve } from 'path'
import kirby from 'vite-plugin-kirby'

export default ({ mode }) => ({
  root: 'src',
  base: mode === 'development' ? '/' : '/dist/',

  build: {
    outDir: resolve(process.cwd(), 'public/dist'),
    emptyOutDir: true,
    rollupOptions: { input: resolve(process.cwd(), 'src/index.js') }
  },

  plugins: [kirby({
    watch: [ 
      '../site/templates/**/*.twig',
      '../site/(snippets|controllers|models)/**/*.php',
      '../content/**/*',
    ],
    kirbyConfigDir: 'app/site/config'
  })],
})
```
The vite.config.php is created.

There's no hurry. If you could take a look at it sometime, I'd be more than happy.

**Comment by arnoson** [comment]
Maybe you can create a simple github repo with the folder strutcure you are using? This would make it much easier for me to check out what is happening :)

**Comment by dannystarkDE** [comment]
Hey :)
https://github.com/dannystarkDE/vitetest/tree/main
thank you very much for your help

**Comment by arnoson** [comment]
I think I solved it: the main problem was that you set the `base` root to your `/app` dir, but the `base` should be your project's root (see `app/public/index.php`). Otherwise it'll be difficult to get all the relative and absolute paths right!

**Comment by dannystarkDE** [comment]
Thanks a million! I didn't even think about the index.php. Or adjusting the plugin path. :)

Do you have a ko-fi link or anything like that? :)
Greetings to Leipzig :)

**Comment by arnoson** [comment]
Glad I could help :) I don't have ko-fi or something similar, but I have Paypal with the email that is listed on my website under `contact` (don't want to post it here in clear text)

**Comment by arnoson** [comment]
oh wow, thank you very much!
