### ISSUE TITLE
Vite 5 support

### ISSUE THREAD

**Issue by thusslack** [arnoson/kirby-vite#42]
There is a breaking change with vite 5: The manifest file generated by vite 5 is located in `.vite/manifest.json` now. (see https://vitejs.dev/config/build-options.html#build-manifest)

**Comment by arnoson** [comment]
Vite 5 is supported since [v5.0.0](https://github.com/arnoson/kirby-vite/releases/tag/v5.0.0) :)
I try to keep the major version numbers in sync with Vite. Which version are you on?

**Comment by arnoson** [comment]
Closing this issue, since it should aready work. Feel free to re-open it if you still have problems with Vite 5!
