### ISSUE TITLE
Make isDev() method public

### ISSUE THREAD

**Issue by s3ththompson** [arnoson/kirby-vite#43]
Currently, the `vite()->isDev()` method is protected. I'd like to be able to call this method in template code from userland.

#### Use case

[`@vitejs/plugin-react`](https://github.com/vitejs/vite-plugin-react) will throw an error if the refresh runtime hook is not [manually included in a server template](https://vitejs.dev/guide/backend-integration.html#backend-integration:~:text=Note%20if%20you%20are%20using%20React%20with%20%40vitejs/plugin%2Dreact). This is a script that should be included in development only, exactly how `@vite/client` is inserted.

**Comment by s3ththompson** [comment]
Happy to submit a PR for the above functionality, if you're open to it!

**Comment by arnoson** [comment]
Seems like a good idea!
