### ISSUE TITLE
Add the requirement for the site/config folder to the readme

### ISSUE THREAD

**Issue by lmgringhuis** [arnoson/kirby-vite#46]
I tried to use Vite in my Kirby site, but just couldn't get it to work. Constantly got this message even though I followed the steps from the readme and the example: 

``` 
error during build:
Error: ENOENT: no such file or directory, open 'site/config/vite.config.php' 
```

Then I found out that the config folder did not yet exist in my kirby/site folder. Maybe good to mention in your readme that the config folder in the site folder is needed to run Kirby Vite? After creating the config folder, the build and vite commands did work.

Perhaps not an issue, but still possibly a useful addition for others in the future!

**Comment by arnoson** [comment]
Thanks for pointing this out! I was mainly using the kirby starter kits for scaffolding and they already have the config folder so I didn't notice. We should definitely point this out in the readme or maybe just create the folder if missing.

**Comment by arnoson** [comment]
Will release this soon :)
