### ISSUE TITLE
str_starts_with(): Argument #1 ($haystack) must be of type string, false given

### ISSUE THREAD

**Issue by Messa1** [arnoson/kirby-vite#47]
I got after kirby update to kirby 4.2.0 this error.
str_starts_with(): Argument #1 ($haystack) must be of type string, false given

site/plugins/kirby-vite/packages/kirby-vite/Vite.php
```
   if (str_starts_with($fullPath, $rootPath)) {
      return ltrim(substr($fullPath, strlen($rootPath)), DIRECTORY_SEPARATOR);
    }
```

my composer

```

"require": {
    "getkirby/cms": "^4.0.0",
    "tobimori/kirby-seo": "^0.4.0",
    "microman/kirby-grid-blocks": "^1.0",
    "bogdancondorachi/kirby-table-field": "^2.3",
    "arnoson/kirby-vite": "^5.3"
  },
```

**Comment by Messa1** [comment]
I did all steps again with the update - now it worsk. Maybe somehting with npm need to check deeper. But i will close it here.

**Comment by arnoson** [comment]
Looks similar to #44, should definitely add better error messages (but am a bit short on time right now ...) Glad everything works again for you!

**Comment by Messa1** [comment]
@arnoson Ok, I tried with your kirby vite start kit - than I got a message on `npm install `, that there are some vulnerabilities and I tried to fix them by using `npm audit fix` that will get me no to the error if I start the app by `npm run dev`
