### ISSUE TITLE
config options not working

### ISSUE THREAD

**Issue by bogdancondorachi** [arnoson/kirby-vite#5]
Hi there, I'm trying to change the entry point through config but it doesn't seem to overwrite the default option which is 'index.js'

`'arnoson/kirby-vite' => [
  'entry' => 'main.jsx',
]`

**Comment by arnoson** [comment]
Ah, my bad, I made a typo in the readme, replace `/` with `.` and it should work:
`'arnoson.kirby-vite' => [ 'entry' => 'main.jsx', ]`

**Comment by bogdancondorachi** [comment]
Thank you, missed that typo as well 😬
