### ISSUE TITLE
Use server origin instead of symlink for assets?

### ISSUE THREAD

**Issue by LeBenLeBen** [arnoson/kirby-vite#8]
The documentation state that a symlink must be created so the web server can access assets, but this solution has a few issues for me:

- I already have an `assets` folder in my `public` directory
- I want to import assets from elsewhere (like `node_modules`) which won’t be available with this technique

I think I was able to achieve the same result without the drawbacks above by using Vite `server.origin` option instead like stated in the [Backend Integration](https://vitejs.dev/guide/backend-integration.html) docs:

```js
export default defineConfig(({ mode }) => ({
  // ...
  server: {
    // ...
    origin: 'http://localhost:3000',
  }
  // ...
}));
```

This ensure that assets URL are prefixed with Vite dev server host so they load properly.

Do you see any issue with this approach I would have overlooked? Would you like me to submit a PR to replace the symlink?

**Comment by arnoson** [comment]
Thank you for mentioning this! I also had some problems with the symlinks. I will test your suggestion and let you know If I find any problems with it

**Comment by arnoson** [comment]
Just had some time to test it and it seems to work great! I'm not sure why I havent used it before, maybe the options wasn't available back then. Would be happy if you submit a PR!
